In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [5]:
# loading dataset

df = pd.read_csv("../data/ecommerce_customer_churn_dataset.csv")
df.head()

,Age,Gender,Country,City,Membership_Years,Login_Frequency,Session_Duration_Avg,Pages_Per_Session,Cart_Abandonment_Rate,Wishlist_Items,...,Email_Open_Rate,Customer_Service_Calls,Product_Reviews_Written,Social_Media_Engagement_Score,Mobile_App_Usage,Payment_Method_Diversity,Lifetime_Value,Credit_Balance,Churned,Signup_Quarter
0,43.0,Male,France,Marseille,2.9,14.0,27.4,6.0,50.6,3.0,...,17.9,9.0,4.0,16.3,20.8,1.0,953.33,2278.0,0,Q1
1,36.0,Male,UK,Manchester,1.6,15.0,42.7,10.3,37.7,1.0,...,42.8,7.0,3.0,NaN,23.3,3.0,1067.47,3028.0,0,Q4
2,45.0,Female,Canada,Vancouver,2.9,10.0,24.8,1.6,70.9,1.0,...,0.0,4.0,1.0,NaN,8.8,NaN,1289.75,2317.0,0,Q4
3,56.0,Female,USA,New York,2.6,10.0,38.4,14.8,41.7,9.0,...,41.4,2.0,5.0,85.9,31.0,3.0,2340.92,2674.0,0,Q1
4,35.0,Male,India,Delhi,3.1,29.0,51.4,NaN,19.1,9.0,...,37.9,1.0,11.0,83.0,50.4,4.0,3041.29,5354.0,0,Q4

In [6]:
df.sample(10)

,Age,Gender,Country,City,Membership_Years,Login_Frequency,Session_Duration_Avg,Pages_Per_Session,Cart_Abandonment_Rate,Wishlist_Items,...,Email_Open_Rate,Customer_Service_Calls,Product_Reviews_Written,Social_Media_Engagement_Score,Mobile_App_Usage,Payment_Method_Diversity,Lifetime_Value,Credit_Balance,Churned,Signup_Quarter
43293,50.0,Male,France,Toulouse,3.3,1.0,18.4,1.6,68.1,2.0,...,1.5,3.0,2.0,6.6,15.1,5.0,422.95,NaN,0,Q1
4723,34.0,Female,Canada,Vancouver,2.7,1.0,18.3,6.1,75.6,3.0,...,0.0,5.0,1.0,17.8,8.5,2.0,795.24,390.0,0,Q3
24202,22.0,Female,Japan,Osaka,2.6,4.0,14.7,8.3,77.5,2.0,...,0.0,10.0,1.0,45.9,10.7,2.0,304.55,150.0,1,Q3
10189,63.0,Female,Germany,Cologne,3.4,17.0,31.1,11.0,33.4,2.0,...,22.5,5.0,5.0,44.3,25.7,1.0,1302.48,1999.0,0,Q1
34792,31.0,Male,Canada,Vancouver,5.8,9.0,13.3,2.4,61.4,0.0,...,4.8,5.0,0.0,0.0,NaN,3.0,699.28,319.0,1,Q2
47425,33.0,Male,Germany,Hamburg,2.8,14.0,39.4,8.8,57.0,4.0,...,2.5,2.0,3.0,24.9,20.4,2.0,3402.06,3505.0,0,Q3
23469,44.0,Female,Germany,Munich,0.9,13.0,11.4,4.4,51.8,6.0,...,0.0,7.0,2.0,0.0,11.8,1.0,1277.74,0.0,0,Q3
12335,22.0,Male,France,Nice,2.5,20.0,41.3,16.5,29.6,9.0,...,24.3,4.0,7.0,71.3,29.7,2.0,2238.96,3432.0,0,Q4
6286,25.0,Male,India,Hyderabad,2.0,22.0,52.4,14.0,27.6,13.0,...,45.3,2.0,10.0,77.4,37.4,3.0,1949.19,4217.0,0,Q4
19386,45.0,Female,USA,New York,6.4,17.0,30.8,11.5,49.4,4.0,...,47.8,2.0,NaN,30.9,27.4,3.0,1673.66,2107.0,0,Q1

In [7]:
df.shape

(50000, 25)

In [ ]:
df.columns.tolist()

['Age',
 'Gender',
 'Country',
 'City',
 'Membership_Years',
 'Login_Frequency',
 'Session_Duration_Avg',
 'Pages_Per_Session',
 'Cart_Abandonment_Rate',
 'Wishlist_Items',
 'Total_Purchases',
 'Average_Order_Value',
 'Days_Since_Last_Purchase',
 'Discount_Usage_Rate',
 'Returns_Rate',
 'Email_Open_Rate',
 'Customer_Service_Calls',
 'Product_Reviews_Written',
 'Social_Media_Engagement_Score',
 'Mobile_App_Usage',
 'Payment_Method_Diversity',
 'Lifetime_Value',
 'Credit_Balance',
 'Churned',
 'Signup_Quarter']

In [10]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 25 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Age                            47505 non-null  float64
 1   Gender                         50000 non-null  str
 2   Country                        50000 non-null  str
 3   City                           50000 non-null  str
 4   Membership_Years               50000 non-null  float64
 5   Login_Frequency                50000 non-null  float64
 6   Session_Duration_Avg           46601 non-null  float64
 7   Pages_Per_Session              47000 non-null  float64
 8   Cart_Abandonment_Rate          50000 non-null  float64
 9   Wishlist_Items                 46000 non-null  float64
 10  Total_Purchases                50000 non-null  float64
 11  Average_Order_Value            50000 non-null  float64
 12  Days_Since_Last_Purchase       47000 non-null  float64
 13  Discount_Usage_Rate            46500 non-null  float64
 14  Returns_Rate                   45509 non-null  float64
 15  Email_Open_Rate                47472 non-null  float64
 16  Customer_Service_Calls         49832 non-null  float64
 17  Product_Reviews_Written        46500 non-null  float64
 18  Social_Media_Engagement_Score  44000 non-null  float64
 19  Mobile_App_Usage               45000 non-null  float64
 20  Payment_Method_Diversity       47500 non-null  float64
 21  Lifetime_Value                 50000 non-null  float64
 22  Credit_Balance                 44500 non-null  float64
 23  Churned                        50000 non-null  int64
 24  Signup_Quarter                 50000 non-null  str
dtypes: float64(20), int64(1), str(4)
memory usage: 9.5 MB

In [11]:
df.Days_Since_Last_Purchase

0        34.0
1        71.0
2        11.0
3        47.0
4        73.0
         ...
49995    18.0
49996    48.0
49997     7.0
49998    72.0
49999    37.0
Name: Days_Since_Last_Purchase, Length: 50000, dtype: float64

In [12]:
# check the missing values

df.isnull().sum()

Age                              2495
Gender                              0
Country                             0
City                                0
Membership_Years                    0
Login_Frequency                     0
Session_Duration_Avg             3399
Pages_Per_Session                3000
Cart_Abandonment_Rate               0
Wishlist_Items                   4000
Total_Purchases                     0
Average_Order_Value                 0
Days_Since_Last_Purchase         3000
Discount_Usage_Rate              3500
Returns_Rate                     4491
Email_Open_Rate                  2528
Customer_Service_Calls            168
Product_Reviews_Written          3500
Social_Media_Engagement_Score    6000
Mobile_App_Usage                 5000
Payment_Method_Diversity         2500
Lifetime_Value                      0
Credit_Balance                   5500
Churned                             0
Signup_Quarter                      0
dtype: int64

In [ ]:
# missing value percentage

df.isnull().mean()*100

Age                               4.990
Gender                            0.000
Country                           0.000
City                              0.000
Membership_Years                  0.000
Login_Frequency                   0.000
Session_Duration_Avg              6.798
Pages_Per_Session                 6.000
Cart_Abandonment_Rate             0.000
Wishlist_Items                    8.000
Total_Purchases                   0.000
Average_Order_Value               0.000
Days_Since_Last_Purchase          6.000
Discount_Usage_Rate               7.000
Returns_Rate                      8.982
Email_Open_Rate                   5.056
Customer_Service_Calls            0.336
Product_Reviews_Written           7.000
Social_Media_Engagement_Score    12.000
Mobile_App_Usage                 10.000
Payment_Method_Diversity          5.000
Lifetime_Value                    0.000
Credit_Balance                   11.000
Churned                           0.000
Signup_Quarter                    0.000
dtype: float64

In [14]:
# check duplicates

df.duplicated().sum()

np.int64(0)

In [18]:
# churned percentage

df['Churned'].value_counts(normalize=True)*100

Churned
0    71.1
1    28.9
Name: proportion, dtype: float64

In [22]:
df.describe()

,Age,Membership_Years,Login_Frequency,Session_Duration_Avg,Pages_Per_Session,Cart_Abandonment_Rate,Wishlist_Items,Total_Purchases,Average_Order_Value,Days_Since_Last_Purchase,...,Returns_Rate,Email_Open_Rate,Customer_Service_Calls,Product_Reviews_Written,Social_Media_Engagement_Score,Mobile_App_Usage,Payment_Method_Diversity,Lifetime_Value,Credit_Balance,Churned
count,47505.000000,50000.000000,50000.000000,46601.000000,47000.000000,50000.000000,46000.000000,50000.000000,50000.000000,47000.000000,...,45509.000000,47472.000000,49832.000000,46500.000000,44000.000000,45000.000000,47500.000000,50000.000000,44500.000000,50000.000000
mean,37.802968,2.984009,11.624660,27.660754,8.737811,57.079973,4.298391,13.111576,123.117330,29.792872,...,6.680913,20.937980,5.681831,2.853312,29.364466,19.371607,2.353874,1440.626292,1966.233258,0.289000
std,11.834668,2.059105,7.810657,10.871013,3.778220,16.282723,3.189754,7.017312,175.569714,29.695062,...,6.143027,14.252561,2.676052,2.328948,20.574021,9.419252,1.110012,907.249443,1225.072166,0.453302
min,5.000000,0.100000,0.000000,1.000000,1.000000,0.000000,0.000000,-13.000000,26.380000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000
25%,29.000000,1.400000,6.000000,19.700000,6.000000,46.400000,2.000000,8.000000,87.050000,9.000000,...,2.900000,9.900000,4.000000,1.000000,13.200000,12.500000,2.000000,789.817500,1049.000000,0.000000
50%,38.000000,2.500000,11.000000,26.800000,8.400000,58.100000,4.000000,12.000000,112.970000,21.000000,...,5.400000,19.700000,5.000000,2.000000,27.600000,18.600000,2.000000,1243.415000,1896.000000,0.000000
75%,46.000000,4.000000,17.000000,34.700000,11.200000,68.700000,6.000000,17.000000,144.440000,41.000000,...,9.100000,30.400000,7.000000,4.000000,43.100000,25.500000,3.000000,1874.000000,2791.000000,1.000000
max,200.000000,10.000000,46.000000,75.600000,24.100000,143.743350,28.000000,128.700000,9666.379178,287.000000,...,99.615734,91.700000,21.000000,21.000000,100.000000,61.900000,5.000000,8987.240000,7197.000000,1.000000

In [23]:
print("Age values > 100:")
print(df[df["Age"] > 100]["Age"].value_counts().sort_index())

print("\nCart abandonment > 100:")
print(df[df["Cart_Abandonment_Rate"] > 100]["Cart_Abandonment_Rate"].describe())

Age values > 100:
Age
150.0     9
200.0    11
Name: count, dtype: int64

Cart abandonment > 100:
count     30.000000
mean     119.661473
std       13.913497
min      100.658972
25%      104.843620
50%      120.617667
75%      129.662012
max      143.743350
Name: Cart_Abandonment_Rate, dtype: float64

In [24]:
df.nunique()

Age                                 62
Gender                               3
Country                              8
City                                40
Membership_Years                   200
Login_Frequency                     46
Session_Duration_Avg               658
Pages_Per_Session                  224
Cart_Abandonment_Rate             1000
Wishlist_Items                      25
Total_Purchases                    150
Average_Order_Value              16407
Days_Since_Last_Purchase           235
Discount_Usage_Rate               1727
Returns_Rate                       394
Email_Open_Rate                    720
Customer_Service_Calls              21
Product_Reviews_Written             18
Social_Media_Engagement_Score      972
Mobile_App_Usage                   540
Payment_Method_Diversity             5
Lifetime_Value                   45447
Credit_Balance                    5234
Churned                              2
Signup_Quarter                       4
dtype: int64

In [50]:
# numerical columns

numeric_col = df.select_dtypes(include="number").columns.drop('Churned')
# numeric_col

for col in numeric_col:
    print(f"\n--------{col}-------")
    print("min :", df[col].min())
    print("max :", df[col].max())

--------Age-------
min : 5.0
max : 200.0

--------Membership_Years-------
min : 0.1
max : 10.0

--------Login_Frequency-------
min : 0.0
max : 46.0

--------Session_Duration_Avg-------
min : 1.0
max : 75.6

--------Pages_Per_Session-------
min : 1.0
max : 24.1

--------Cart_Abandonment_Rate-------
min : 0.0
max : 143.74335014288403

--------Wishlist_Items-------
min : 0.0
max : 28.0

--------Total_Purchases-------
min : -13.0
max : 128.70000000000002

--------Average_Order_Value-------
min : 26.38
max : 9666.37917838422

--------Days_Since_Last_Purchase-------
min : 0.0
max : 287.0

--------Discount_Usage_Rate-------
min : 0.24
max : 116.64

--------Returns_Rate-------
min : 0.0
max : 99.6157338622138

--------Email_Open_Rate-------
min : 0.0
max : 91.7

--------Customer_Service_Calls-------
min : 0.0
max : 21.0

--------Product_Reviews_Written-------
min : 0.0
max : 21.0

--------Social_Media_Engagement_Score-------
min : 0.0
max : 100.0

--------Mobile_App_Usage-------
min : 0.0
max : 61.9

--------Payment_Method_Diversity-------
min : 1.0
max : 5.0

--------Lifetime_Value-------
min : 0.0
max : 8987.24

--------Credit_Balance-------
min : 0.0
max : 7197.0

In [51]:
# categorical columns

categorical_col = df.select_dtypes(include=['object','string']).columns
categorical_col

for col in categorical_col:
    print(f"\n-------{col}------")
    print(df[col].nunique())
    print(df[col].unique())

-------Gender------
3
<StringArray>
['Male', 'Female', 'Other']
Length: 3, dtype: str

-------Country------
8
<StringArray>
['France', 'UK', 'Canada', 'USA', 'India', 'Japan', 'Germany', 'Australia']
Length: 8, dtype: str

-------City------
40
<StringArray>
[  'Marseille',  'Manchester',   'Vancouver',    'New York',       'Delhi',
       'Tokyo',      'Berlin',     'Houston',     'Calgary',     'Glasgow',
      'Munich',     'Phoenix',       'Paris',      'Ottawa', 'Los Angeles',
   'Bangalore',    'Adelaide',    'Yokohama',      'Sydney',      'Nagoya',
   'Frankfurt',     'Cologne',     'Hamburg',        'Nice',     'Chicago',
    'Toulouse',    'Brisbane',       'Leeds',      'Mumbai',    'Montreal',
   'Melbourne',       'Osaka',        'Lyon',   'Hyderabad',     'Chennai',
  'Birmingham',      'London',     'Toronto',       'Perth',       'Kyoto']
Length: 40, dtype: str

-------Signup_Quarter------
4
<StringArray>
['Q1', 'Q4', 'Q2', 'Q3']
Length: 4, dtype: str

In [52]:
# data quality

print("age >100 :",(df['Age'] > 100).sum())
print("Cart_Abandonment_Rate > 100 :", (df["Cart_Abandonment_Rate"] > 100).sum())
print("Total_Purchases < 0 :", (df['Total_Purchases'] < 0).sum())
print("Discount_Usage_Rate > 100 :", (df['Discount_Usage_Rate'] > 100).sum())

age >100 : 20
Cart_Abandonment_Rate > 100 : 30
Total_Purchases < 0 : 40
Discount_Usage_Rate > 100 : 207

In [53]:
# missing values

for col in numeric_col:
    print(f"Missing values in {col}")
    print(df.groupby(df[col].isna())['Churned'].mean())

Missing values in Age
Age
False    0.290896
True     0.252906
Name: Churned, dtype: float64
Missing values in Membership_Years
Membership_Years
False    0.289
Name: Churned, dtype: float64
Missing values in Login_Frequency
Login_Frequency
False    0.289
Name: Churned, dtype: float64
Missing values in Session_Duration_Avg
Session_Duration_Avg
False    0.280080
True     0.411297
Name: Churned, dtype: float64
Missing values in Pages_Per_Session
Pages_Per_Session
False    0.289617
True     0.279333
Name: Churned, dtype: float64
Missing values in Cart_Abandonment_Rate
Cart_Abandonment_Rate
False    0.289
Name: Churned, dtype: float64
Missing values in Wishlist_Items
Wishlist_Items
False    0.288957
True     0.289500
Name: Churned, dtype: float64
Missing values in Total_Purchases
Total_Purchases
False    0.289
Name: Churned, dtype: float64
Missing values in Average_Order_Value
Average_Order_Value
False    0.289
Name: Churned, dtype: float64
Missing values in Days_Since_Last_Purchase
Days_Since_Last_Purchase
False    0.288638
True     0.294667
Name: Churned, dtype: float64
Missing values in Discount_Usage_Rate
Discount_Usage_Rate
False    0.290968
True     0.262857
Name: Churned, dtype: float64
Missing values in Returns_Rate
Returns_Rate
False    0.288031
True     0.298820
Name: Churned, dtype: float64
Missing values in Email_Open_Rate
Email_Open_Rate
False    0.282735
True     0.406646
Name: Churned, dtype: float64
Missing values in Customer_Service_Calls
Customer_Service_Calls
False    0.288770
True     0.357143
Name: Churned, dtype: float64
Missing values in Product_Reviews_Written
Product_Reviews_Written
False    0.288151
True     0.300286
Name: Churned, dtype: float64
Missing values in Social_Media_Engagement_Score
Social_Media_Engagement_Score
False    0.287932
True     0.296833
Name: Churned, dtype: float64
Missing values in Mobile_App_Usage
Mobile_App_Usage
False    0.289178
True     0.287400
Name: Churned, dtype: float64
Missing values in Payment_Method_Diversity
Payment_Method_Diversity
False    0.289537
True     0.278800
Name: Churned, dtype: float64
Missing values in Lifetime_Value
Lifetime_Value
False    0.289
Name: Churned, dtype: float64
Missing values in Credit_Balance
Credit_Balance
False    0.288315
True     0.294545
Name: Churned, dtype: float64

In [56]:
df.loc[df['Total_Purchases'] < 0, ['Total_Purchases','Average_Order_Value','Returns_Rate','Churned']]

       Total_Purchases  Average_Order_Value  Returns_Rate  Churned
2875              -9.1               285.01           9.8        1
4082              -6.0               141.30           4.3        0
4329             -10.4               106.64           8.9        0
5040             -11.7               172.67           8.7        0
7820              -3.0                64.59           8.2        0
9813              -1.0               134.10           4.1        0
10167             -2.6               183.97           3.9        0
11467            -11.7               140.18           7.9        0
11678            -10.0               175.03           5.5        1
12452             -5.2               168.84           1.1        0
13170             -7.0               182.91           1.8        0
14017             -4.0               123.90           9.7        0
14175             -5.0               190.91           9.0        1
15644             -6.0               107.00           7.6        0
20547            -10.0               133.93           8.9        1
21219            -10.0                99.93           4.6        0
21543             -6.5                87.84           4.1        0
26346             -6.5               113.71           NaN        0
26949             -6.0                75.35           8.6        0
27637             -7.8                81.47           8.6        0
27737             -1.0                90.84           4.4        0
32985             -4.0               116.75           8.4        0
33066             -6.5                63.16           8.8        0
35922             -3.0               110.41           4.8        0
36057             -7.0                62.52           3.4        0
36086             -8.0               158.32           6.5        0
36414             -5.0                78.20          10.6        0
37686             -7.8               138.46           NaN        0
38212             -7.0               102.37           NaN        0
38234             -2.0               188.21           NaN        0
38286             -2.6               121.08           1.7        0
38617             -4.0                91.08           6.6        1
38988             -8.0               114.93           7.4        0
39901             -7.8               164.56           5.9        0
41273             -2.0               101.19           3.9        0
44346            -13.0               114.47           4.5        1
45661             -3.0                72.45           6.6        0
46176             -7.0               286.12          10.8        1
47440             -3.0               231.26          18.6        0
49338             -8.0               219.96           NaN        0

In [57]:
negative_purchases = df["Total_Purchases"] < 0

print("Number of invalid rows:", negative_purchases.sum())
print("Percentage of dataset:", negative_purchases.mean() * 100)

print("\nChurn rate of invalid rows:")
print(df.loc[negative_purchases, "Churned"].mean())

print("\nChurn rate of valid rows:")
print(df.loc[~negative_purchases, "Churned"].mean())

Number of invalid rows: 40
Percentage of dataset: 0.08

Churn rate of invalid rows:
0.175

Churn rate of valid rows:
0.28909127301841475

In [58]:
checks = {
    "Age > 100": df["Age"] > 100,
    "Cart_Abandonment_Rate > 100": df["Cart_Abandonment_Rate"] > 100,
    "Discount_Usage_Rate > 100": df["Discount_Usage_Rate"] > 100
}

for name, condition in checks.items():
    print(f"\n--- {name} ---")
    print("Invalid rows:", condition.sum())
    print("Percentage:", condition.mean() * 100)
    print("Churn rate:", df.loc[condition, "Churned"].mean())

--- Age > 100 ---
Invalid rows: 20
Percentage: 0.04
Churn rate: 0.2

--- Cart_Abandonment_Rate > 100 ---
Invalid rows: 30
Percentage: 0.06
Churn rate: 0.26666666666666666

--- Discount_Usage_Rate > 100 ---
Invalid rows: 207
Percentage: 0.414
Churn rate: 0.2898550724637681

In [59]:
df["Total_Purchases"].loc[
    ~df["Total_Purchases"].isna() &
    (df["Total_Purchases"] % 1 != 0)
].count()

np.int64(11241)

In [60]:
decimal_purchases = df.loc[
    ~df["Total_Purchases"].isna() &
    (df["Total_Purchases"] % 1 != 0),
    "Total_Purchases"
]

print(decimal_purchases.describe())
print("\nSample values:")
print(decimal_purchases.head(20).to_list())

count    11241.000000
mean        15.753118
std          8.469995
min        -11.700000
25%         10.400000
50%         15.600000
75%         20.800000
max        128.700000
Name: Total_Purchases, dtype: float64

Sample values:
[19.5, 9.1, 32.5, 14.3, 6.5, 22.1, 15.6, 19.5, 15.6, 23.4, 14.3, 16.900000000000002, 15.6, 10.4, 29.9, 10.4, 19.5, 23.4, 11.7, 2.6]

In [61]:
print(
    df.loc[
        df["Total_Purchases"] % 1 != 0,
        "Total_Purchases"
    ].head(50).to_list()
)

[19.5, 9.1, 32.5, 14.3, 6.5, 22.1, 15.6, 19.5, 15.6, 23.4, 14.3, 16.900000000000002, 15.6, 10.4, 29.9, 10.4, 19.5, 23.4, 11.7, 2.6, 24.7, 19.5, 31.200000000000003, 20.8, 19.5, 15.6, 9.1, 16.900000000000002, 31.200000000000003, 7.800000000000001, 15.6, 9.1, 19.5, 3.9, 7.800000000000001, 10.4, 24.7, 7.800000000000001, 6.5, 15.6, 16.900000000000002, 16.900000000000002, 28.6, 9.1, 11.7, 9.1, 20.8, 9.1, 16.900000000000002, 14.3]

In [62]:
print("Unique values:", df["Total_Purchases"].nunique())

print("\nMost common values:")
print(df["Total_Purchases"].value_counts().head(20))

Unique values: 150

Most common values:
Total_Purchases
13.0    3231
9.0     2676
10.0    2634
11.0    2625
12.0    2500
8.0     2470
7.0     2295
14.0    2155
15.0    2002
6.0     1982
16.0    1731
5.0     1660
17.0    1509
18.0    1336
4.0     1188
19.0    1118
20.0     921
11.7     886
10.4     874
14.3     857
Name: count, dtype: int64

In [63]:
df.groupby(df["Total_Purchases"] % 1 != 0)["Churned"].mean()

Total_Purchases
False    0.288423
True     0.290988
Name: Churned, dtype: float64

In [64]:
invalid_membership = df["Membership_Years"] > df["Age"]

print("Invalid rows:", invalid_membership.sum())
print("Percentage:", invalid_membership.mean() * 100)

print("\nExamples:")
print(df.loc[invalid_membership, ["Age", "Membership_Years", "Churned"]].head(20))

Invalid rows: 5
Percentage: 0.01

Examples:
       Age  Membership_Years  Churned
1745   5.0              10.0        1
27132  5.0               5.1        1
36476  5.0               6.0        0
37311  5.0               7.8        0
47187  5.0               7.1        0

In [66]:
print("Age < 13:", (df["Age"] < 13).sum())
print("Age < 18:", (df["Age"] < 18).sum())

print("\nAge < 13 records:")
print(
    df.loc[df["Age"] < 13,
           ["Age", "Membership_Years", "Total_Purchases", "Churned"]]
)

Age < 13: 30
Age < 18: 30

Age < 13 records:
        Age  Membership_Years  Total_Purchases  Churned
709     5.0               0.6             12.0        1
1745    5.0              10.0              6.0        1
2616   10.0               2.0              5.0        1
7019    5.0               2.1             19.5        0
7315   10.0               0.6              7.0        1
7817    5.0               1.9             12.0        1
9391    5.0               3.4             31.2        1
10985  10.0               2.3             11.0        1
11531  10.0               2.8              6.0        0
12019   5.0               2.5              7.0        1
13863   5.0               0.9             21.0        1
13930  10.0               4.8              8.0        1
14206  10.0               1.4              6.0        1
14373  10.0               3.0              9.0        0
14964  10.0               1.1             10.0        1
17913   5.0               0.7              6.0        1
18719   5.0               0.3             11.0        0
19864  10.0               2.3             29.9        0
26852   5.0               4.2             16.9        0
27132   5.0               5.1             20.8        1
29360  10.0               0.3              9.0        1
33397   5.0               4.0             15.0        1
33678  10.0               1.8             25.0        0
36476   5.0               6.0              9.0        0
36948  10.0               2.2              7.0        1
37311   5.0               7.8             12.0        0
39696  10.0               2.5              6.0        0
47187   5.0               7.1             22.0        0
48086  10.0               4.1             13.0        0
49200   5.0               3.8             20.0        0

In [73]:
df['Age'].value_counts().sort_index()

Age
5.0        16
10.0       14
18.0     2639
19.0      493
20.0      550
         ...
73.0       27
74.0       11
75.0       45
150.0       9
200.0      11
Name: count, Length: 62, dtype: int64

In [74]:
print(df["Customer_Service_Calls"].describe())

count    49832.000000
mean         5.681831
std          2.676052
min          0.000000
25%          4.000000
50%          5.000000
75%          7.000000
max         21.000000
Name: Customer_Service_Calls, dtype: float64

In [77]:
check = (df["Total_Purchases"] == 0) & df["Days_Since_Last_Purchase"].notna()

print("Customers with 0 purchases but a last-purchase value:",
      check.sum())

print(df.loc[check,
             ["Total_Purchases", "Days_Since_Last_Purchase", "Churned"]].head(20))

Customers with 0 purchases but a last-purchase value: 9
       Total_Purchases  Days_Since_Last_Purchase  Churned
2198               0.0                      28.0        1
15196              0.0                       2.0        0
15794              0.0                      13.0        1
23747              0.0                      21.0        1
31584              0.0                       1.0        1
32581              0.0                      23.0        1
33939              0.0                       0.0        1
38702              0.0                      10.0        1
40098              0.0                      20.0        1